x-versions: &versions
  R_VERSION: "4.4"

services:
  rstudio:
    build:
      args: *versions
      context: .
      dockerfile: Dockerfile
    environment:
      - DISABLE_AUTH=true
    ports:
      - "127.0.0.1:8787:8787"
    volumes:
      - ~/.Rprofile:/home/rstudio/.Rprofile
      - ./.rstudio_config:/home/rstudio/.config/rstudio
      - ./workspace:/home/rstudio/workspace
      - ./data:/home/rstudio/data